### ISSUE TITLE
Error building next app

### ISSUE THREAD

**Issue by matthieuh** [tamagui/starters#5]
Running `yarn build` from the `/next` folder i'm getting this error:
```
SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.newLoader (/Users/matthieuh/workspace/perso/starters/next-expo-solito/node_modules/esbuild-register/dist/node.js:2262:9)
    at Object.extensions..js (/Users/matthieuh/workspace/perso/starters/next-expo-solito/node_modules/esbuild-register/dist/node.js:4801:24)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at ChildProcess.listener (/Users/matthieuh/workspace/perso/starters/next-expo-solito/node_modules/@tamagui/static/dist/cjs/extractor/getStaticBindingsForScope.js:68:13)
 ```
    
I'm trying to build next on this commit: https://github.com/tamagui/starters/commit/33e7fe0e9dc141e9130054b01e4efbafa6ff47b0

**Comment by natew** [comment]
@matthieuh can you try the new version, I think we've fixed this.

**Comment by matthieuh** [comment]
I confirm it now works! Great job you are doing with Tamagui 💜
